### ISSUE TITLE
RIFE denoise

### ISSUE THREAD

**Issue by DTL2020** [Asd-g/AviSynthPlus-RIFE#2]
Can this script be put in compiled form:
function RIFE_degrain1(clip src)
{
ConvertToRGB(src)
ConvertToPlanarRGB()
ConvertBits(32)
src32=last
even=SelectEvery(2,0)
odd=SelectEvery(2,1) 
even_d=RIFE(even)
odd_d=RIFE(odd)
even_d=SelectEvery(even_d,2,1)
odd_d=SelectEvery(odd_d,2,1)
den_int=Interleave(even_d, odd_d).Trim(1,0)
src32_trim=Trim(src32,1,0)
den_int2=Average(den_int, 0.666, src32_trim, 0.3333)
return den_int2.ConvertToRGB24().ConvertToYV12()
}
? 
May be as addional mode to this plugin or separate .dll.

And may be a bit increased options for 'larger temporal radius' like 2 or 3 or more. It may help to performance by decreasing AVS+ cashing inbetween script objects.

Also for AVS users the current documentation is a bit unclear - the 32bit RGB may be RGBA 8bit but RIFE only accepts RGBPS float32 planar format. May be add some example script or direct note about 32bit mean float32 each RGB channel samples encoding - not 8bit integer with 4 samples per RGBA pack.

**Comment by DTL2020** [comment]
As I see the original rife-ncnn-vulkan https://github.com/nihui/rife-ncnn-vulkan is simple (2 frames in -> 1 frame out) interpolation engine. So the script above is tr=1 temporal denoise using formula

out_frame = current_frame * (1/3) + rife_ncnn(+1, -1) * (2/3)

where rife_ncnn(+1, -1) = RIFE of pair of frames -1 (previous) and +1 (next) from current frame number. Using default 0.5 internal temporal param (calculate exactly intermediate frame of 2 input frames).

For better denosing with possible still not very great artifacts more tr-modes possible like tr=2 :

out_frame = current_frame * (1/5) + rife_ncnn(+1, -1) * (2/5) + rife_ncnn(+2, -2) * (2/5)

so for tr=N : 
out_frame = sum _N (current_frame * (1/(N_mul_2+1)) + rife_ncnn(+1, -1) * (2/(N_mul_2+1)) +...+ rife_ncnn(+N, -N) * (2/ (N_mul_2+1)) 

and so on. With AVS scripting it is more hard to simulate but with program compiled form is much easier.

**Comment by Asd-g** [comment]
At first look I would leave the colorspace conversions for the other tools.

I have to look at the rest but no eta.

**Comment by DTL2020** [comment]
Yes - it is enough if RIFE plugin will continue accept its 32bit float RGB.
Only need to add logic for fetching interpolated result from different
pairs of previous and next frames from RIFE and calculate weighted average
with the RIFE results and current frame. In float32 it is very easy and
precise.

**Comment by Asd-g** [comment]
> Also for AVS users the current documentation is a bit unclear - the 32bit RGB may be RGBA 8bit but RIFE only accepts RGBPS float32 planar format. May be add some example script or direct note about 32bit mean float32 each RGB channel samples encoding - not 8bit integer with 4 samples per RGBA pack.

RGBA 8bit (RGB32) is not planar format.
From the  readme `It must be in RGB 32-bit planar format.`  - implies `rgbps`/`rgbaps`. Or I missing something?

**Comment by DTL2020** [comment]
For old AVS users 32bit format typically mean RGBA32. Yes - it is not planar. But 32bit RGB planar also may be unclear - like 32bit integer samples format. It is good to add note about float 32bit samples RGB planar (separated planes).

**Comment by jonashed** [comment]
This is very interesting, is it going to happen?
Is it possible to use another method (maybe optional with a 'filterClip') such as temporalsoften or other temporal filters than average? In the same manner as mvtools mcompensated-Temporaldenoiser-selectevery().

**Comment by Asd-g** [comment]
@DTL2020, try the attached version. There is additional bool parameter `denoise`. Currently it does the exactly same operations as the script function from the first comment. It requires the plugin `Average`. Eventually that dependency could be removed.

https://github.com/Asd-g/AviSynthPlus-RIFE/tree/denoise

[RIFE_denoise.zip](https://github.com/Asd-g/AviSynthPlus-RIFE/files/10690051/RIFE_denoise.zip)

**Comment by DTL2020** [comment]
I do not have access to required GPU hardware to test so I ask users at
doom9 forum to make test.

I think with compiled implementation may be it is not required to duplicate
full script structure and only make call to RIFE (-1, +1) frame creation
for Average() processing ? With RIFE (-1, +1) I mean call to RIFE with a
pair of frames of -1 and +1 number from current requested frame number. So
RIFE will recreate interpolated frame (from previous and next) at timestamp
of 'current' frame for Average() to finish work of averaging (previous,
current, next) frames. If it possible with current RIFE implementation. May
be it will save lots of hardware resources if skip creation of non-needed
frames in 2 RIFE calls and SelectEvery() ? Or AVS engine do not really
request non-needed frame numbers and no resources wasted ?
As I remember from testing scripted denoise form it require lots of
hardware resources and can run at 6 GB GPU board with 1920x1080 frames with
only 3 threads (4 or more threads already can cause out of resources error).

**Comment by Asd-g** [comment]
RIFE (-1, +1) in one pass isn't possible. You can take a look at https://github.com/Asd-g/AviSynthPlus-RIFE/blob/main/src/rife.cpp#L352

The script implementation with prefetch(3) - GPU mem ~4500MB, RAM ~3300MB.
RIFE(denoise=true) with prefetch(3) - GPU mem ~3800MB, RAM ~2300MB.

Btw my GPU (RX480 8GB) is already saturated with prefetch(2).
The script implementation with prefetch(2) - GPU mem ~4000MB, RAM ~2500MB.
RIFE(denoise=true) with prefetch(2) - GPU mem ~2800MB, RAM ~1700MB.

Above tests are made with 1080p video and default RIFE model.

**Comment by DTL2020** [comment]
As I see in RIFE_process() it accept src0, src1 and dst pointers as input
params. So it was idea that RIFE takes only 2 input frames and timing
information in between (in the 0..1 float internal) for creation of output
frame (so it create motion estimation and compensation based only on 2
input frames only ?). Or it really takes and analyses (>2 frames) sequence
of many sequential frames to create the requested interpolated frame
between provided 0 and 1 src frames for RIFE_process()? I still not
understand completely how that RIFE_process() works.
If it takes only 2 frames - so it was idea in compiled form it is possible
to request 2 frames of -1 and +1 from previous filter and pass to
single RIFE processing environment. So it should save from creating 2
streams of half frame numbers and 2 RIFE processing streams to create both
even and odd interpolated frames and possibly save half of hardware and
compute resources, Only put workarounds to 0 and last output frame for
which -1 and +1 source frames not exist - simply replace -1 frame with
current for 0 output frame and +1 with current for last output frame.

In the AVS scripting form I think AVS caching may force 2 RIFE filters to
fill some cache buffers with every sequential frame and make 2x redundant
work because only half of frames from 2 RIFE streams actually requested for
Average().

**Comment by DTL2020** [comment]
Also as stated in the 'source of RIFE'
https://github.com/nihui/rife-ncnn-vulkan -
Usages

Input two frame images, output one interpolated frame image.

So it can run in 2-input frames mode only (not large sequence to analyse).
Or it is not kept in current AVS plugin implementation ? This 2-input
frames mode only is all that required for 3-frames denoise. I use 2 streams
of RIFE processing in scripting form only because I do not know how to
request -1 and +1 frames from current frame in scripting and also old
RIFE_AVS implementation only accepts clip sequence of frames and not pairs
of given frames as in the RIFE-vulcan we see. So if using RIFE-vulcan
2-input frames mode only it is possible to run compiled RIFE_denoise with
single RIFE processing environment and save half of resources ?

It expected in compiled form sort of:

GetFrame(n)

{

prev_frame = GetFrame(src_filter, n-1)

next_frame= GetFrame(src_filter, n+1)

current_frame = GetFrame(src_filter, n)

int_frame = RIFE(src0 = prev_frame, src1 = next_frame, time=0.5f)

output=Average(current_frame, weight 0.333, int_frame, weight 0.666)

}

**Comment by Asd-g** [comment]
> s(o it create motion estimation and compensation based only on 2
input frames only ?)

> So it can run in 2-input frames mode only (not large sequence to analyse).

Yes, it's 2-input frames mode only.

> So it can run in 2-input frames mode only (not large sequence to analyse).

You already have [n](https://github.com/Asd-g/AviSynthPlus-RIFE/blob/main/src/plugin.cpp#L146) and [n+1](https://github.com/Asd-g/AviSynthPlus-RIFE/blob/main/src/plugin.cpp#L332) by default. So for `denoise=true` you want `n-1` (`auto src0{ avs_get_frame(fi->child, frameNum - 1) };`)  (with adjusted timestep) instead `n` (`auto src0{ avs_get_frame(fi->child, frameNum) };`)?

**Comment by DTL2020** [comment]
Yes - for complete internal denoise with tr=1 we need to request 3 frames
from AVS environment:
n-1 is avs_get_frame(fi->child, frameNum - 1)
n is avs_get_frame(fi->child, frameNum)
n+1 is avs_get_frame(fi->child, frameNum + 1)

Frames n-1 and n+1 we send to RIFE_process and result of RIFE and n we send
to our simple linear blending engine Average().
It is simplest form but work only nice if RIFE provide ideal motion
compensation.
So some users may want to use more advanced non-linear blending engine in
AVS scripting so it may be good do add more control param like
'denoise_blending_mode' of 'average' or 'none'
In 'none' mode we simply output RIFE processed interpolated frame so user
can apply it into more advanced blending plugin/filter to attempt to save
from bad blends where RIFE fails significantly with motion compensation.
Also for experiments if may be added control param like 'denoise_tr' with
default of 1 and use it instead of +-1 in frames request for RIFE
interpolation.
So user may want to test more deep denoise in scripting with requesting
different interpolation 'temporal radius' of >1. Though the quality of
interpolation may quickly degrades with increasing tr but 2 may be still
working not very bad. So it will be possible to create more simple denoise
scripts like
int_tr1=RIFE(denoise=true, denoise_blending_mode=none, tr=1)
int_tr2=RIFE(denoise=true, denoise_blending_mode=none, tr=2)
Average(last, 1/5, int_tr1, 2/5, int_tr2, 2/5)
To simulate MDegrain2 activity. Also user can use other non-linear blending
instead of Average().

For the processing optimization it is better to perform Average() math
inside hardware accelerator and upload n-frame too for Average(). In
sequential AVS processing it is possible to upload 1 src frame and download
1 output frame for each output frame to have minimal possible bus traffic.
With uploaded resources referencing - for output frame n+1 our previously
uploaded resources is:
n-1 - skip
n become n-1 for RIFE input
n+1 become n for Average() input
uploaded next frame - become n+1 for RIFE input
and so on. So it need 3 frame resources in hardware accelerator buffer with
'shifting' for each next output denoised frame.

**Comment by Asd-g** [comment]
Try the attached version. It should be used only for denoising.
`denoise` parameter is removed.
New parameter `denoise_tr`. Default 1, it must be greater than 0.
New parameter `denoise_blending_mode`. `0` - average (still average plugin required); `1` - none. Default 0.

[RIFE_denoise1.zip](https://github.com/Asd-g/AviSynthPlus-RIFE/files/10763526/RIFE_denoise1.zip)

**Comment by DTL2020** [comment]
The invernal blending looks like work good. At GTX1060 6 GB card its compute1 performance counter reach 100% at Prefetch(2) so any other increasing threads number in AVS+ not increase script fps and only increase GPU memory load and afterPrefetch(4) start to crash with vk_exceptions (like out of memory errors). CPU load is only 5%.

But when I try output frames for external blending something strange happens with AVS+ environment - it looks the 'last' variable get all frames processed by RIFE calls (or even sum of 'last' and RIFE) so Average() plugin not work because clips number of frames not equal:
Here is attempts:
ConvertToRGB()
ConvertToPlanarRGB()
ConvertBits(32)

src_den=last
#return last.ConvertToRGB24().ConvertToYV12()

tr1=RIFE(denoise_tr=1, denoise_blending_mode=1)
tr2=RIFE(denoise_tr=2, denoise_blending_mode=1)

return src_den.ConvertToRGB24().ConvertToYV12()

Average(src_den, 0.3333, tr1, 0.6666)

#Average(last, 0.2, tr1, 0.4, tr2, 0.4)

ConvertToRGB24()
ConvertToYV12()

Before RIFE calls the last is frame count 1978, after single RIFE call 'src_den' clip is 3956 frames. After dual RIFE calls src_den clip is 7912 frames.
Even simple return src_den.ConvertToRGB24().ConvertToYV12() after RIFE() calls return clip with frame number about several times more in compare with 'last' before RIFE calls. So all Average() calls for both tr1 and tr1+tr2 not work with either 'last' or even 'src_den' clip taken 'before' RIFE calls. Maybe RIFE with denoise_blending_mode=1 somehow corrupt AVS+ environment ? I use AVS+ version 3.7.3 (r3820, 3.7, x86_64)

**Comment by DTL2020** [comment]
As a temporal workaround I try Trim() 'last' clip close to its real number or frames before Average and it finally start to work:

src_den=last

tr1=RIFE(denoise_tr=1, denoise_blending_mode=1)
tr2=RIFE(denoise_tr=2, denoise_blending_mode=1)
tr3=RIFE(denoise_tr=2, denoise_blending_mode=1)

src_den=Trim(src_den, 0, 1700)

Average(src_den, 0.1428, tr1, 0.2857, tr2, 0.2857, tr3, 0.2857)

ConvertToRGB24()
ConvertToYV12()

AssumeFPS(50)

At least tr=3 is working OK. But the resulted 'last' clip got fps of about 400 as reported by VirtualDub - so I also need to assume it back to 50. So the RIFE calls somehow change fps of the AVS environment too.

At Win10 with 16 GB RAM and GTX1060 6 GB it work now up to tr6 looks like good, tr7 output no-colour and low Y values and crashes. At least working is
src_den=last

tr1=RIFE(denoise_tr=1, denoise_blending_mode=1)
tr2=RIFE(denoise_tr=2, denoise_blending_mode=1)
tr3=RIFE(denoise_tr=3, denoise_blending_mode=1)
tr4=RIFE(denoise_tr=4, denoise_blending_mode=1)
tr5=RIFE(denoise_tr=5, denoise_blending_mode=1)
tr6=RIFE(denoise_tr=6, denoise_blending_mode=1)

src_den=Trim(src_den, 0, 1700)

w6_1=1.0/13.0
w6_res=2.0/13.0
Average(src_den, w6_1, tr1, w6_res, tr2, w6_res, tr3, w6_res, tr4, w6_res, tr5, w6_res, tr6, w6_res)

With Prefetch(2)

When using Prefetch(1) it can go up to tr12 still working - good enough.

**Comment by Asd-g** [comment]
> But when I try output frames for external blending something strange happens with AVS+ environment - it looks the 'last' variable get all frames processed by RIFE calls (or even sum of 'last' and RIFE) so Average() plugin not work because clips number of frames not equal:

It seems that fps/num_frames are from the rife processing and not from the postprocessing (selectodd is used). I'll take a look later.

**Comment by DTL2020** [comment]
The scene change detect engine looks like need significant enhancement - with default sc_threshold of 0.12 it looks still not detect at all and with 0.005 it start to skip RIFE process and things become soft. May be in current build scene detect engine not adapted for 'high-tr' ? When scene change detected in the +-tr interval (or between -tr and +tr frames pair ?) - do it return 'current/N' frame or what ? I think if scene change detected in the +-tr interval - for denoising it may be 'fail safe' to return current frame (in denoise_blending_mode=1). It will decrease denoising activity near scene change timestampts but will not cause possible bad blends or bad interpolation between scenes.

**Comment by Asd-g** [comment]
Try the attached version. `sc` and `skip` should be fine now for `denoise_tr=1`. Also the issue about fps/num_frames should be fixed. Added back parameter `denoise` (default false).

[RIFE_denoise2.zip](https://github.com/Asd-g/AviSynthPlus-RIFE/files/10774595/RIFE_denoise2.zip)

**Comment by DTL2020** [comment]
Do I need to enable 'skip' param to get better avoiding interpolation on scene changes ? It require addtional VMAF2 plugin ? Or it is not used if 'denoise=true' ? My content typically do not have duplicated frames so either all valid frames need RIFE or if scene-change detected - simply return (or put to Average) current frame. Or VMAF2 plugin can help to scene detection if 'skip' enabled ?

As I see from last commit - https://github.com/Asd-g/AviSynthPlus-RIFE/blob/e714d8fa8ebc7a2d38bd729a642a86370dfb3261/src/plugin.cpp#L383 it is something about VMAF2 plugin and getting psnrY for scene detection ? Also do it mean new fixed scene detection only works with +-1 tr and not (yet) work for tr > 1 ?

**Comment by DTL2020** [comment]
After some testing: This version have enhancement in scene change detection _before_ scene change but with tr=1 and internal blending and skip=true (VMAF plugin loaded) still produce 1 error-blended frame right after scene change (also with lowered sc_threshold).

So string

RIFE(denoise=true, denoise_tr=1, denoise_blending_mode=0, skip=true, sc=true, sc_threshold=0.1)

looks like still not detect some scenechange example and produce 2 error-blended frames  - 1 before and 1 after scene change.

At the same scenechange string

RIFE(denoise=true, denoise_tr=1, denoise_blending_mode=0, skip=true, sc=true, sc_threshold=0.01)

looks like detect scenechange OK but produce 1 error-blended (interpolated from 2 scenes) frame after scenechange. May be still some issue remains in the handling scenechange algorithm ?

Next testing with external blending engine:
tr1=RIFE(denoise=true, denoise_tr=1, denoise_blending_mode=1, skip=true, sc=true, sc_threshold=0.01)

Interleave(tr1, last, tr1)
MedianBlurTemporal(radiusy=0, radiusu=0, radiusv=0, temporalradius=1)
SelectEvery(3, 1)

Here we have both frames before and after scenechange good clean. So it may be issue of after-scenechange error-blending frame only apply to internal call to Average ?

With attempt:
tr1=RIFE(denoise=true, denoise_tr=1, denoise_blending_mode=1, skip=true, sc=true, sc_threshold=0.01)
Average(last, 0.33333, tr1, 0.6666)
1 error-blended frame still exist at scenechange. May be in above example with 3 filters chain it fixed by MedianBlurTemporal() interlnally ?

**Comment by Asd-g** [comment]
> Do I need to enable 'skip' param to get better avoiding interpolation on scene changes ? It require addtional VMAF2 plugin ? Or it is not used if 'denoise=true' ? My content typically do not have duplicated frames so either all valid frames need RIFE or if scene-change detected - simply return (or put to Average) current frame. Or VMAF2 plugin can help to scene detection if 'skip' enabled ?

`skip` is opposite to `sc`. Frames with no motion, almost identical will be not be interpolated. VMAF2 is required for `skip`. 

> As I see from last commit - https://github.com/Asd-g/AviSynthPlus-RIFE/blob/e714d8fa8ebc7a2d38bd729a642a86370dfb3261/src/plugin.cpp#L383 it is something about VMAF2 plugin and getting psnrY for scene detection ? Also do it mean new fixed scene detection only works with +-1 tr and not (yet) work for tr > 1 ?

Yes, this line is only for VMAF2/psnrY.

Try the attached version. `sc` should be ok now and it works for any `denoise_tr`.

[RIFE_denoise3.zip](https://github.com/Asd-g/AviSynthPlus-RIFE/files/10775185/RIFE_denoise3.zip)

**Comment by DTL2020** [comment]
It looks version 3 works as expected now. Tested with some scenechanges and now all frames good - before and after scenechange. I also try to ask RIFE developers about more dedicated mode of motion compensation for denoise.

**Comment by Asd-g** [comment]
I'm considering to remove parameter `denoise_blending_mode`. Output will be only interpolated frames when `denoise=true` and the user can use whatever he wants for the further filtering. Currently `denoise_blending_mode=0` is exactly `denoise_blending_mode=1` and calling filter Average. Yes, Average can be implemented in order to avoid the call of the external plugin but the impact (memory/speed) will be minimal.

Also implemented `skip=true` for any `denoise_tr`.

**Comment by DTL2020** [comment]
I agree - Average() is the simplest linear blending engine possible and return the lowest quality. So may be in most use cases the users will use much more advanced external blending engines so the 'denoise_blending_mode=0' with internal call to external Average() plugin may be removed.

**Comment by DTL2020** [comment]
Can not found direct way to contact via e-mail. It is a VS-to-AVSport request of the also hardware-accelerated plugin for motion compensation using NVIDIA Optical Flow (though looks like limited to NVIDIA hardware only). I found some in-development plugin for Vapoursynth only about NVIDIA optical flow - https://bitbucket.org/mystery_keeper/vapoursynth-nvof/src/master/

It is not very old and have some activity in 2022. Can you port it to Avisynth so we can test it in temporal denoising too ?
Though in readme.txt it is still marked as not very production-ready. May be quality is still not very good. But quality may be mostly depend on NVIDIA progress in Optical Flow implementation in hardware and drivers.

**Comment by Asd-g** [comment]
I don't have NVIDIA GPU. I prefer to not touch such plugins/code that I cannot test.
